#!/usr/bin/env bash
# load-secrets.sh — pull Key Vault secrets for each Supabase project, write
# /opt/supabase-{project}/.env consumed by Docker Compose env_file, and
# generate Kong declarative config with actual API keys.
#
# Runs via managed identity — no credentials or storage keys required.
# Called by supabase-secret-loader.service before docker.service starts.
#
# Required env:
#   KEYVAULT_NAME  — Azure Key Vault name (e.g. "kv-constellation")
#   PROJECTS       — space-separated list of project slugs (e.g. "constellation")
#   DNS_ZONE       — DNS zone for URL generation (e.g. "db.harebrained-apps.com")
#
# Key Vault secret naming convention (per project):
#   {PROJECT_UPPER}-JWT-SECRET         → JWT_SECRET
#   {PROJECT_UPPER}-ANON-KEY           → ANON_KEY
#   {PROJECT_UPPER}-SERVICE-ROLE-KEY   → SERVICE_ROLE_KEY
#   {PROJECT_UPPER}-POSTGRES-PASSWORD  → POSTGRES_PASSWORD
#   {PROJECT_UPPER}-DASHBOARD-USERNAME → DASHBOARD_USERNAME
#   {PROJECT_UPPER}-DASHBOARD-PASSWORD → DASHBOARD_PASSWORD
#   {PROJECT_UPPER}-SMTP-HOST          → SMTP_HOST
#   {PROJECT_UPPER}-SMTP-PORT          → SMTP_PORT
#   {PROJECT_UPPER}-SMTP-USER          → SMTP_USER
#   {PROJECT_UPPER}-SMTP-PASS          → SMTP_PASS
#   {PROJECT_UPPER}-SMTP-SENDER-NAME   → SMTP_SENDER_NAME
#
# Shared secrets (not project-scoped):
#   RESEND-API-KEY                     → RESEND_API_KEY (written to shared.env)

set -euo pipefail

: "${KEYVAULT_NAME:?KEYVAULT_NAME must be set}"
: "${PROJECTS:?PROJECTS must be set}"
: "${DNS_ZONE:?DNS_ZONE must be set}"

echo "Authenticating with managed identity..."
az login --identity --allow-no-subscriptions >/dev/null 2>&1

# Mapping from Key Vault secret suffix to Docker Compose env var name
declare -A SECRET_MAP=(
  [JWT_SECRET]=JWT_SECRET
  [ANON_KEY]=ANON_KEY
  [SERVICE_ROLE_KEY]=SERVICE_ROLE_KEY
  [POSTGRES_PASSWORD]=POSTGRES_PASSWORD
  [DASHBOARD_USERNAME]=DASHBOARD_USERNAME
  [DASHBOARD_PASSWORD]=DASHBOARD_PASSWORD
  [SMTP_HOST]=SMTP_HOST
  [SMTP_PORT]=SMTP_PORT
  [SMTP_USER]=SMTP_USER
  [SMTP_PASS]=SMTP_PASS
  [SMTP_SENDER_NAME]=SMTP_SENDER_NAME
)

# Critical secrets that MUST exist — fail hard if missing
CRITICAL_SECRETS=(JWT_SECRET ANON_KEY SERVICE_ROLE_KEY POSTGRES_PASSWORD)

for project in $PROJECTS; do
  project_upper="${project^^}"
  env_dir="/opt/supabase-${project}"
  env_file="${env_dir}/.env"
  kong_dir="${env_dir}/volumes/api"

  mkdir -p "$env_dir" "$kong_dir"
  # Write atomically: build to a temp file then move
  tmp_file=$(mktemp "${env_dir}/.env.XXXXXX")
  chmod 600 "$tmp_file"

  echo "# Auto-generated by load-secrets.sh — do not edit" > "$tmp_file"
  echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$tmp_file"

  # Track values needed for kong.yml generation
  declare -A fetched_values=()

  for secret_suffix in "${!SECRET_MAP[@]}"; do
    kv_secret_name="${project_upper}-${secret_suffix//_/-}"
    env_var_name="${SECRET_MAP[$secret_suffix]}"

    secret_value=$(az keyvault secret show \
      --vault-name "$KEYVAULT_NAME" \
      --name "$kv_secret_name" \
      --query "value" \
      --output tsv 2>/dev/null) || {
      echo "WARNING: secret ${kv_secret_name} not found in ${KEYVAULT_NAME}, skipping" >&2
      continue
    }

    printf '%s=%s\n' "$env_var_name" "$secret_value" >> "$tmp_file"
    fetched_values["$secret_suffix"]="$secret_value"
  done

  # Validate critical secrets exist
  missing=()
  for cs in "${CRITICAL_SECRETS[@]}"; do
    if [[ -z "${fetched_values[$cs]:-}" ]]; then
      missing+=("$cs")
    fi
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "FATAL: missing critical secrets: ${missing[*]}" >&2
    rm -f "$tmp_file"
    exit 1
  fi

  # Write URL config (derived from project name + DNS zone)
  project_url="https://${project}.${DNS_ZONE}"
  printf 'API_EXTERNAL_URL=%s\n' "$project_url" >> "$tmp_file"
  printf 'SITE_URL=%s\n' "$project_url" >> "$tmp_file"
  printf 'SUPABASE_PUBLIC_URL=%s\n' "$project_url" >> "$tmp_file"

  mv "$tmp_file" "$env_file"
  echo "Wrote ${env_file}"

  # Generate Kong declarative config with actual API keys
  anon_key="${fetched_values[ANON_KEY]}"
  service_key="${fetched_values[SERVICE_ROLE_KEY]}"
  kong_file="${kong_dir}/kong.yml"

  cat > "$kong_file" <<KONG_EOF
_format_version: "1.1"

consumers:
  - username: DASHBOARD
  - username: anon
    keyauth_credentials:
      - key: ${anon_key}
  - username: service_role
    keyauth_credentials:
      - key: ${service_key}

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/verify
    plugins:
      - name: cors

  - name: auth-v1-open-callback
    url: http://auth:9999/callback
    routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths:
          - /auth/v1/callback
    plugins:
      - name: cors

  - name: auth-v1-open-authorize
    url: http://auth:9999/authorize
    routes:
      - name: auth-v1-open-authorize
        strip_path: true
        paths:
          - /auth/v1/authorize
    plugins:
      - name: cors

  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
      - name: cors

  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
      - name: cors

  - name: realtime-v1
    url: http://realtime:4000/socket/
    routes:
      - name: realtime-v1
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
      - name: cors

  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
      - name: cors

  - name: meta
    url: http://meta:8080/
    routes:
      - name: meta
        strip_path: true
        paths:
          - /pg/
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
KONG_EOF

  chmod 600 "$kong_file"
  echo "Wrote ${kong_file}"
done

# Shared secret: RESEND_API_KEY (written to /opt/supabase-shared/shared.env)
mkdir -p /opt/supabase-shared
shared_tmp=$(mktemp "/opt/supabase-shared/.shared.env.XXXXXX")
chmod 600 "$shared_tmp"
echo "# Shared secrets — do not edit" > "$shared_tmp"

resend_key=$(az keyvault secret show \
  --vault-name "$KEYVAULT_NAME" \
  --name "RESEND-API-KEY" \
  --query "value" \
  --output tsv 2>/dev/null) || true
[ -n "${resend_key:-}" ] && printf 'RESEND_API_KEY=%s\n' "$resend_key" >> "$shared_tmp"

mv "$shared_tmp" /opt/supabase-shared/shared.env
echo "Wrote /opt/supabase-shared/shared.env"

echo "Secret loading complete."
