#!/usr/bin/env bash
# load-secrets.sh — pull Key Vault secrets for each Supabase project and write
# /opt/supabase-{project}/.env consumed by Docker Compose env_file.
#
# Runs via managed identity — no credentials or storage keys required.
# Called by supabase-secret-loader.service before docker.service starts.
#
# Required env:
#   KEYVAULT_NAME  — Azure Key Vault name (e.g. "constellation-kv")
#   PROJECTS       — space-separated list of project slugs (e.g. "constellation")
#
# Key Vault secret naming convention (per project):
#   {PROJECT_UPPER}_JWT_SECRET         → JWT_SECRET
#   {PROJECT_UPPER}_ANON_KEY           → ANON_KEY
#   {PROJECT_UPPER}_SERVICE_ROLE_KEY   → SERVICE_ROLE_KEY
#   {PROJECT_UPPER}_POSTGRES_PASSWORD  → POSTGRES_PASSWORD
#   {PROJECT_UPPER}_DASHBOARD_USERNAME → DASHBOARD_USERNAME
#   {PROJECT_UPPER}_DASHBOARD_PASSWORD → DASHBOARD_PASSWORD
#   {PROJECT_UPPER}_SMTP_HOST          → SMTP_HOST
#   {PROJECT_UPPER}_SMTP_PORT          → SMTP_PORT
#   {PROJECT_UPPER}_SMTP_USER          → SMTP_USER
#   {PROJECT_UPPER}_SMTP_PASS          → SMTP_PASS
#   {PROJECT_UPPER}_SMTP_SENDER_NAME   → SMTP_SENDER_NAME

set -euo pipefail

: "${KEYVAULT_NAME:?KEYVAULT_NAME must be set}"
: "${PROJECTS:?PROJECTS must be set}"

# Mapping from Key Vault secret suffix to Docker Compose env var name
declare -A SECRET_MAP=(
  [JWT_SECRET]=JWT_SECRET
  [ANON_KEY]=ANON_KEY
  [SERVICE_ROLE_KEY]=SERVICE_ROLE_KEY
  [POSTGRES_PASSWORD]=POSTGRES_PASSWORD
  [DASHBOARD_USERNAME]=DASHBOARD_USERNAME
  [DASHBOARD_PASSWORD]=DASHBOARD_PASSWORD
  [SMTP_HOST]=SMTP_HOST
  [SMTP_PORT]=SMTP_PORT
  [SMTP_USER]=SMTP_USER
  [SMTP_PASS]=SMTP_PASS
  [SMTP_SENDER_NAME]=SMTP_SENDER_NAME
)

for project in $PROJECTS; do
  project_upper="${project^^}"
  env_dir="/opt/supabase-${project}"
  env_file="${env_dir}/.env"

  mkdir -p "$env_dir"
  # Write atomically: build to a temp file then move
  tmp_file=$(mktemp "${env_dir}/.env.XXXXXX")
  chmod 600 "$tmp_file"

  echo "# Auto-generated by load-secrets.sh — do not edit" > "$tmp_file"
  echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$tmp_file"

  for secret_suffix in "${!SECRET_MAP[@]}"; do
    kv_secret_name="${project_upper}-${secret_suffix//_/-}"
    env_var_name="${SECRET_MAP[$secret_suffix]}"

    secret_value=$(az keyvault secret show \
      --vault-name "$KEYVAULT_NAME" \
      --name "$kv_secret_name" \
      --query "value" \
      --output tsv 2>/dev/null) || {
      echo "WARNING: secret ${kv_secret_name} not found in ${KEYVAULT_NAME}, skipping" >&2
      continue
    }

    printf '%s=%s\n' "$env_var_name" "$secret_value" >> "$tmp_file"
  done

  mv "$tmp_file" "$env_file"
  echo "Wrote ${env_file}"
done

echo "Secret loading complete."
